baseURL = "https://invisible.ch/"
title = "Invisible"
copyright = "Copyright © 2018, Jens-Christian Fischer"
languageCode = "en-US"
theme = "indigo"

[params]
  Author = "Jens-Christian Fischer"
  Description = "Description of website for head meta tag"
  Subtitle = "Musings. Music. Code. Art"
  Avatar = "images/site-logo.svg"
  Biography = "A short description, a few sentences describing the author. Set the 'ShowBio' parameter to false to hide this."
  ShowBio = false
  PermalinkText = "🔗"

  # Contact/social-network identifiers for social icons
  EmailAddress = "jens-christian@invisible.ch"
  FacebookUser = "FacebookUserName"
  FlickrUser = "FlickrUserName"
  GitHubUser = "jcfischer"
  GitLabUser = "jcfischer"
  GlitchUser = "GlitchUserName"
  KeybaseUser = "jcfischer"
  LinkedInUser = "LinkedInUserName"
  MediumUser = "MediumUserName"
  TwitterUser = "jcfischer"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]
    EmailAddress = "jens-christian@invisible.ch"
    FlickrUser = "FlickrUserName"
    GitHubUser = "jcfischer"
    TwitterUser = "jcfischer"
    Country = "Switzerland"
    City = "Zurich"
