baseurl         = "https://invisible.ch"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[author]
    name    = "Jens-Christian Fischer"
    nick    = "jcfischer"
    email   = "jens-christian@invisible.ch"
    avatar  = ""
    description = "Maker. Musician"

[params]
  title       = "Invisible"
  subtitle    = "Musings. Music. Code. Art"
  copyright   = "© 2018"

  cover       = "img/blog-cover.jpg"
  description = "Portfolio and Blog of Jens-Christian Fischer"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "jcfischer"
  fbName = "JensChristianFischer"
  githubName = "jcfischer"
  linkedinName = "jenscfischer"
  keybaseName = "jcfischer"


  showSupport = false

  author = "EM"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[taxonomies]
  tag = "tags"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Musings"
  url = "/musings"
  weight = 200

[[menu.main]]
  name = "Music"
  url = "/music"
  weight = 100

[[menu.main]]
  name = "Code"
  url = "/code"
  weight = 99

[[menu.main]]
  name = "Art"
  url = "/art"
  weight = 95

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 90


# These are parameters used for indieweb identity. You should set these along
# with the above email/social network parameters.
[params.indieWeb]
    Country = "Switzerland"
    City = "Zurich"
    webmention = "invisible.ch"
