baseurl = "https://invisible.ch/"
title = "Musings. Music. Code. Art"
theme = "invisible"
languageCode = "en-us"
copyright = "Jens-Christian Fischer"
disqusShortname = "XXX"
googleAnalytics = "XXX"

[Privacy]

[Privacy.disqus]
    disable = true

[Privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = false

[Author]
    name = "Jens-Christian Fischer"
    profile = "https://google.com/+XXX"
    email = "jens-christian@invisible.ch"
    nick = "jcfischer"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Ghostwriter example"
    description = "Ghostwriter example description"
    github = "https://github.com/jcfischer"
    gitlab = "https://gitlab.com/XXX"
    linkedin = "https://linkedin.com/in/jenscfischer/"
    twitter = "https://twitter.com/jcfischer"
    stackoverflow = "https://stackoverflow.com/users/XXX/YYY"
    microblog = "https://micro.blog/XXX"
    webmentionEndpoint = "https://example.com/webmention"
    pingbackEndpoint = "https://example.com/pingback"
    micropubEndpoint = "https://example.com/webmention/micropub"
    email = "jens-christian@invisible.ch"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    musings = "/:year/:month/:day/:filename/"

[taxonomies]
    tag = "tags"
    archive = "archives"

[[menu.main]]
    name = "Musings"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Music"
    url = "/music/"
    weight = 2

[[menu.main]]
    name = "Code"
    url = "/code/"
    weight = 3

[[menu.main]]
    name = "Art"
    url = "/art/"
    weight = 4
