baseurl         = "https://invisible.ch/"
title           = "Invisible - Musings. Music. Code. Art"
theme           = ["hugo-atom-feed", "casper-two"]
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
canonifyurls    = true


[outputs]
    # <domain>/atom.xml
    home = ["HTML", "RSS", "ATOM"]     # default = ["HTML", "RSS"]
    # <domain>/posts/atom.xml
    section = ["HTML", "RSS", "ATOM"]  # default = ["HTML", "RSS"]
    # <domain>/tags/mytag/atom.xml, <domain>/categories/mycat/atom.xml
    taxonomy = ["HTML", "RSS", "ATOM"] # default = ["HTML", "RSS"]

[authorInfo]
    name    = "Jens-Christian Fischer"
    nick    = "jcfischer"
    email   = "jens-christian@invisible.ch"
    avatar  = ""
    description = "Maker. Musician"

[params]
  title       = "Invisible"
  subtitle    = "Musings. Music. Code. Art"
  copyright   = "© 2018"

  cover       = "img/blog-cover.jpg"
  description = "Portfolio and Blog of Jens-Christian Fischer"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  mainSections = ["musings", "music", "code", "art"]

  twitterName = "jcfischer"
  fbName = "JensChristianFischer"
  githubName = "jcfischer"
  linkedinName = "jenscfischer"
  keybaseName = "jcfischer"


  showSupport = false

  author = "EM"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://eueung.github.io"
  authorDescription = "Your description here"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"


[permalinks]
  posts = "/:year/:month/:slug/"

[[menu.main]]
  name = "Musings"
  url = "/categories/musings"
  weight = 200

[[menu.main]]
  name = "Music"
  url = "/categories/music"
  weight = 100

[[menu.main]]
  name = "Code"
  url = "/categories/code"
  weight = 99

[[menu.main]]
  name = "Art"
  url = "/categories/art"
  weight = 95

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 90


# These are parameters used for indieweb identity. You should set these along
# with the above email/social network parameters.
[params.indieWeb]
    Country = "Switzerland"
    City = "Zurich"
    webmention = "invisible.ch"
