baseurl         = "https://invisible.ch/"
title           = "Invisible"
theme           = [ "chaschper", "matomo" ]
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
canonifyurls    = true
enableRobotsTXT = true
assetDir        = "static"
timeout         = 30000

[author]
    name    = "Jens-Christian Fischer"
    nick    = "jcfischer"
    email   = "jens-christian@invisible.ch"
    avatar  = "/images/jcf_square_256.jpg"
    description = "Maker. Musician"

[params]
  title       = "InVisible"
  domain      = "invisible.ch"
  subtitle    = "Musings. Music. Code. Art"
  copyright   = "© 2003 – 2022"

  cover       = "img/blog-cover.jpg"
  description = "Portfolio and Blog of Jens-Christian Fischer"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""
  showSubcribe = true
  show_reading_time = true

  mainSections = ["musings", "music", "code", "art"]

  twitterName = "jcfischer"
  mastodonName = "social.invisible.ch/@jcfischer"
  fbName = "JensChristianFischer"
  githubName = "jcfischer"
  linkedinName = "jenscfischer"
  keybaseName = "jcfischer"
  flickrName = "jcfischer"


  pageNotFoundTitle = "404 - Page not found"

  googleSiteVerification = "TrRJwBFj-oKRaKg9YbzfGu6IHS7qDYBGHcZjkEAIkWA"
  yandexSiteVerification = "f222468042a995be"

[permalinks]
  posts = "/:year/:month/:slug/"
  blog   = "/:year/:month/:day/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1000

[[menu.main]]
  name = "Musings"
  url = "/categories/musings"
  weight = 200

[[menu.main]]
  name = "Music"
  url = "/categories/music"
  weight = 101

[[menu.main]]
  name = "Galleries"
  url = "/galleries"
  weight = 100


[[menu.main]]
  name = "Code"
  url = "/categories/code"
  weight = 99

[[menu.main]]
  name = "Art"
  url = "/categories/art"
  weight = 95

[[menu.main]]
  name = "Now"
  url = "/now"
  weight = 92

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 90


# These are parameters used for indieweb identity. You should set these along
# with the above email/social network parameters.
[params.IndieWeb]
    Country = "Switzerland"
    City = "Zurich"
    webmention = "invisible.ch"

[params.matomo]
    url = "https://matomo.invisible.ch"
    id = 1

[params.matomo.track]
    button = "Enable Analytics"
    message = "Your visits will be logged."
[params.matomo.block]
    button = "Disable Analytics"
    message = "Your visits will *not* be logged."


[markup.goldmark.renderer]
unsafe = true
